# Generated by Django 5.2 on 2025-04-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='Name',
        ),
    ]
