# Generated by Django 5.2 on 2025-04-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0003_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='Comment',
            field=models.CharField(max_length=200),
        ),
    ]
