# Generated by Django 5.2 on 2025-04-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0004_alter_reviews_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
